sudo: false
dist: trusty
language: python
python:
  - '3.5'
  - '3.6'
env:
  matrix:
    - DJANGO_VERSION='>=1.11,<1.12'
    #- DJANGO_VERSION='>=2.0,<2.1'
addons:
  postgresql: '9.5'
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
install:
  - pip install --upgrade pip
  - pip install -e .[development]
  - "pip install Django$DJANGO_VERSION"
script:
  - coverage run --source=uk_geo_utils --omit=uk_geo_utils/tests/*.py,uk_geo_utils/migrations/*.py,uk_geo_utils/fixtures/*.py run_tests.py
after_success:
  - coveralls
